script/hooks/keyboards-build-success.php, script/model/model.php, script/model/model_search.php, tools/db/build/build.php, tools/db/build/build_models_script.php, tools/db/build/model-queries.sql, tools/db/build/search.sql, tools/db/servervars.php, tools/util.php, web.config
api.keyman.com/model?q=bcp47:km,en-AU will return all models for Khmer and Australian English. Note that the API should return models for en as well as en-AU; the consumer of the API should determine which it wants to present to the user. A given model may be registered for en-US and en in order to be available as a fallback for other English queries.
After installing a language and/or keyboard, this will be the search pattern used by Keyman apps.
**Implemented 2019-03-01**:
* q=bcp47:code - for all models that list that single BCP47 code explicitly.
**To do**:
* q=bcp47:code,code - multiple bcp47 codes
* q=bcp47:lang-region - matching on lang as well as lang-region
api.keyman.com/model?q=nrc will return all models that match the search string nrc. This will search against text fields in …
=> [api.keyman.com] Add models to database and support /model api endpoint

schemas/package/1.1.0/package.json, schemas/readme.MD
This doesn't increment the version number, as the metadata was in a pre-release version. However, instead of removing the `version` field entirely, I've made it optional so that schema validation for existing packages does not fail. This may not be 100% ideal but is a non-breaking change to the schema.
See also keymanapp/keyman#2164.
=> Make 'version' property optional in package.json schema

tools/db/build/build_keyboards_script.php, tools/db/build/build_models_script.php, tools/db/build/build_standards_data_script.php
A recently uploaded keyboard had a lowercase 'fr-ca' instead of 'fr-CA' and this impacted the sort order and merge of results in such a way as to result in repeated keys, breaking the JSON standard:
```
[…
{name: "French (Canada)", id: "fr-CA", region: 4, keyboards: [,…]},
{name: "French (Canada)", id: "fr-ca", region: 4,…},
{name: "French (Canada)", id: "fr-CA", region: 4,…},
…]
```
This change reduces all BCP 47 tags to lowercase in the database.
=> fix: case-sensitive BCP 47 subtags are breaking API search and consistency

script/legacy/legacy20.php, script/legacy/legacy30.php, script/legacy/legacy40.php, tools/onlineupdate.php
Fixes #22.
Fixes #23.
Online Update Check was causing logs to fill up due to
file_get_contents emitting a warning on a 400 or 404.
The legacy KeymanWeb APIs were emitting notices when looking up
fonts and examples for languages that were not set.
=> fix: spurious warnings filling logs

script/legacy/legacy40.php, script/legacy/legacy_db.php, tools/db/build/legacy-queries.sql
Addresses issues with performance for looking up all keyboards, e.g. as
used by KeymanWeb:
https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=12.0.103&timerid=6
This would result in about 630 separate queries, one for the list of
keyboards, and one for each keyboard returned to get the list of
languages associated with the keyboards. The fix reduces this to
two queries: one for the keyboards, and one for the languages.
This appears to be correlated to a massive increase in data egress on
api.keyman.com MySQL database instance; while the queries themselves
amounted to about 1.3mb of data, each call would result in 80mb of
outbound traffic. This may be due to some configuration change on the
database as it has only arisen recently.
In any case, …
=> fix: all keyboards lookup performance

script/legacy/legacy30.php, script/legacy/legacy40.php, script/legacy/legacy_db.php, tools/db/build/legacy-queries.sql
`getLanguages()` was also very slow in legacy30 and legacy40, for opposite
reason of the last commit: in this case everything was being returned in
one monolithic query which duplicated data heavy fields, resulting in a
70MB query result, which was transformed finally into a 270KB JSON result.
Splitting this query into 2 queries allowed for normalization of this data;
this query was also suffering from the same issue in legacy30.php as was
fixed in legacy40.php in #24, which creates a massive performance hit
(namely spurious Notices when looking up missing fonts/examples).
=> fix: Improve performance of legacy/languages

web.config
Fixes keymanapp/keyman.com#53.
This PR makes 13.0 and future version endpoints work transparently, so we don't need to update them for each release.
=> fix: add 13.0+ api endpoints

tools/db/build/build_keyboards_script.php
This transforms all .keyboard_info language bcp 47 tags to lower case when the database is generated to simplify legacy queries later.
=> fix: lower case keyboard_info bcp47 tags on import

schemas/keyboard_info.distribution/1.0.5/keyboard_info.distribution.json, schemas/keyboard_info.source/1.0.5/keyboard_info.source.json, schemas/readme.MD, schemas/search/1.0.2/search.json, schemas/search/1.0/search.json, schemas/web.config, script/search/search.php, tools/db/.gitignore, tools/db/build/build.php, tools/db/build/build_keyboards_script.php, tools/db/build/build_models_script.php, tools/db/build/build_standards_data_script.php, tools/db/build/common.php, tools/db/build/search-prepare-data.sql, tools/db/build/search-queries.sql, tools/db/build/search.sql, tools/db/servervars.php, tools/util.php
Backend changes relating to keymanapp/keyman.com#62
Adds deprecation state to the database and surfaces it 
in the keyboard search. This leads to a slight difference
in .keyboard_info and API data.
Fixes #5.
Fixes #7.
Fixes #29.
=> fix: add deprecated state for keyboards

tools/db/build/build_keyboards_script.php, tools/db/build/build_models_script.php
Fixes #27. Model info BCP 47 tags now use lower
case always to simplify search and match. Also
tweaked keyboard_info transform to cope with
bare array form of languages value, although at
current time this is never used in the database.
=> fix: lower case bcp 47 for models

tools/db/build/build_keyboards_script.php, tools/db/build/legacy-queries.sql
Fixes #38.
Deprecated keyboards are no longer included in search results when using
the legacy APIs. This reduces the result set for Android, iOS and
KeymanWeb pickers.
Also, adds Linux platform data to the keyboard metadata.
=> fix: ignore deprecated keyboards in legacy APIs

tools/db/build/legacy-queries.sql
Fixes #40. When doing language-specific queries, or keyboard-specific
queries, need to return deprecated keyboards as well as current ones.
=> fix: legacy queries need to return deprecated keyboards in some cases

tools/db/build/search.sql, tools/db/db.php
Fixes #41. MySQL by default doesn't support
supplementary planes with its UTF-8 charset.
Instead need to use utf8mb4...
=> fix: default charset to utf8mb4

schemas/keyboard_info.source/1.0.6/keyboard_info.source.json, script/keyboard/keyboard.inc.php, script/keyboard/keyboard.php, tests/KeyboardTest.php
This also reverts a mistake in the keyboard_info schema where certain fields that are in use were deleted (scriptName, regionName, languageName).
See also documentation update at https://github.com/keymanapp/help.keyman.com/pull/185
=> feat: initial test case for /keyboard

schemas/package/1.1.0/package.json
One small tweak to our KMP schema's JSON and we can achieve draft-04 compliance, which is quite significant given how many tools out there target this draft but not later ones.
=> change: package schema now draft-04 compliant

composer.json, composer.lock, tests/rest/RestTestCase.php, tests/rest/RestVersionTest.php, tools/util.php
This adds the `RestTestCase` class with assertion helpers for JSON schema and standard headers, and adds additional test cases for the version API that use these helpers.
=> feat: groundwork for rest-based test cases

schemas/search/2.0/search.json, script/search/2.0/search.inc.php, tests/fixtures/Search.2.0.ethiopic.json, tests/fixtures/Search.2.0.khmer.json, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_id.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql, tools/db/build/sp_keyboard_search_by_legacy_id.sql
This will allow us to link the language tag in automatically when installing a keyboard so the correct association is made.
Part of solution for keymanapp/keyman#1456.
=> feat: add bcp47 tag for language results

schemas/keyboard_info.source/1.0.6/keyboard_info.source.json, schemas/search/2.0/search.json, script/search/2.0/search.inc.php, tests/fixtures/Search.2.0.ethiopic.json, tests/fixtures/Search.2.0.khmer-angkor.json, tests/fixtures/Search.2.0.khmer-keyboards.json, tests/fixtures/Search.2.0.khmer.json, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_id.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql, tools/db/build/sp_keyboard_search_by_legacy_id.sql
Improves schema validation and fixes the field types for the match object.
Then, tidy up fixtures to match the tweaked schema requirements.
Removing `additionalProperties` from keyboard_info.source.json means we can extend the schema as we do with the search schema -- and in other places, potentially. It may be worthwhile at some point defining a base schema file for the various types we have scattered around api.keyman.com, where `additionalProperties` is never specified, and refactoring the schema definitions to refer to those base schema types instead. But this is a sizeable chunk of work for limited end-user benefit...
=> fix: schema value types for match fields

schemas/keyboard_info.source/1.0.6/keyboard_info.source.json, schemas/search/2.0/search.json, script/search/2.0/search.inc.php, tests/fixtures/Search.2.0.ethiopic.json, tests/fixtures/Search.2.0.khmer-angkor.json, tests/fixtures/Search.2.0.khmer-keyboards.json, tests/fixtures/Search.2.0.khmer.json, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_id.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql, tools/db/build/sp_keyboard_search_by_legacy_id.sql
Give higher weight to shorter matches, so 'spa' matches 'Spanish' rather than a variant name. Do this only for language names
=> fix: adjust langtag search weight

schemas/keyboard_info.source/1.0.6/keyboard_info.source.json, script/search/2.0/search.inc.php, tests/Search20Test.php, tools/db/LangTags.php, tools/db/build/build_keyboards_script.inc.php, tools/db/build/langtags.sql, tools/db/build/search-prepare-data.sql, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_popularity.sql
During import, if a bcp47 tag is found that is not in
langtags, a custom entry will be added. Similarly, if
a name is found that is not currently in langtags, it
will be added as a custom name. Tests updated accordingly.
=> feat: support custom language names and tags

schemas/keyboard_info.source/1.0.6/keyboard_info.source.json, script/search/2.0/search.inc.php, tests/Search20Test.php, tools/db/LangTags.php, tools/db/build/build_keyboards_script.inc.php, tools/db/build/langtags.sql, tools/db/build/search-prepare-data.sql, tools/db/build/sp_country_search_10.sql, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_popularity.sql, tools/db/build/sp_language_search_10.sql
For example, a search for 'callejon' would fail because the
language name was too long after concatenation: "Quechua, Northern
Conchucos Ancash (Quechua del Norte del Callejon de Conchucos)".
=> fix: some searches failed with truncation

.github/workflows/ci.yml, script/hooks/keyboards-build-success.php, tests/TestDBBuild.inc.php, tests/data/README.md, tools/db/.gitignore, tools/db/build/build.inc.php, tools/db/build/build_cli.php, tools/db/build/build_models_script.inc.php, tools/db/build/build_standards_data_script.inc.php, tools/db/build/cjk/build.inc.php, tools/db/build/clean-database.sql, tools/db/build/common.inc.php, tools/db/build/create-database.sql, tools/db/build/full-text-indexes.sql, tools/db/build/indexes.sql, tools/db/build/search.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql, tools/db/db.php, tools/db/servervars.php
Relates to #87.
This reduces our database requirement to a single database, which will reduce run costs on Azure.
So a SQL Server 'schema' is effectively a namespace within a database. Objects in SQL Server are referred to with up to two qualifiers before the name: `[database_name].[schema_name].[object_name]`.
This PR is moving down our active/inactive database pairs down one level in "namespacing" from database level to schema level.
The reason we have two schemas is this way we can build a whole new database (which is entirely static data, remember), on an inactive schema, and then swap over in a single (atomic) statement, without impacting use of the database at all in the interim.
If you have setup a local instance, you'll need to adjust the following environment variables / …
=> refactor: use schemas instead of swappable databases

tests/Search20Test.php, tests/fixtures/Search.2.0.ethiopic.json, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
Relates to #87.
This updates the search algorithm to return the matched keyboard's registered BCP 47 tag rather than the normalised BCP 47 tag that is used for the search, in the `match.tag` field, so that the tag can be passed as a initial parameter to the apps for installing the keyboard.
This means that a search may involve up to three different forms of the same tag:
* The searched tag, e.g. `str-latn-ca`
* The normalised tag, e.g. `str`
* The keyboard's registered tag, e.g. `str-latn`
The presentation of the results hides most of these details from the user.
=> fix(search): use keyboard's BCP 47 tag in links

script/search/2.0/search.inc.php, script/search/2.0/search.php, tests/Search20Test.php, tools/db/build/build_keyboards_script.inc.php, tools/db/build/search-prepare-data.sql, tools/db/build/search.sql, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_by_country.sql, tools/db/build/sp_keyboard_search_by_country_iso3166_code.sql, tools/db/build/sp_keyboard_search_by_id.sql, tools/db/build/sp_keyboard_search_by_keyboard.sql, tools/db/build/sp_keyboard_search_by_language.sql, tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql, tools/db/build/sp_keyboard_search_by_legacy_id.sql, tools/db/build/sp_keyboard_search_by_popularity.sql, tools/db/build/sp_keyboard_search_by_script.sql, tools/db/build/sp_keyboard_search_by_script_iso15924_code.sql
The search now skips deprecated and non-Unicode keyboards by default. Passing the parameter obsolete=1 will list all keyboards including obsolete ones. Obsolete keyboards will always be listed last.
Front end on keyman.com keymanapp/keyman.com#147
Relates to #87.
=> fix: skip deprecated keyboards

schemas/README.md, schemas/model-search/1.0.1/model-search.json, schemas/model_info.distribution/1.0.1/model_info.distribution.json, schemas/model_info.source/1.0.1/model_info.source.json, schemas/package-version/1.0.1/package-version.json, schemas/web.config, script/model-search/model-search.inc.php, script/model/model.inc.php, script/package-version/package-version.inc.php, tests/ModelSearchTest.php, tests/ModelTest.php, tests/PackageVersionTest.php, tools/2020/KeymanUrls.php
Fixes #58.
Part of #102. 
* Fixes /go/package URLs for /model?q= and /model/id endpoints.
* Adds a property `deprecatedBy` to the package-version endpoint.
* Also fixes some issues with package-version schema and tests.
* Refactors one URL builder to KeymanUrls.php.
I can split this into two PRs if you insist!
=> feat: use go/package for models and package-version

tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
Fixes #112. When searching by langid, obsolete keyboards were included in statistics even though they were not listed.
=> fix: obsolete keyboards in stats

script/desktop/10.0/submitdiag/index.php
Fixes keymanapp/keyman#3673.
Discourse's API authentication has changed, so we needed to rework to remove old ways of doing things. Also tweaked some of the error handling to make it slightly easier to track in the future.
=> fix: diagnostic endpoint discourse update

App_Data/jobs/continuous/database_build/README.md, App_Data/jobs/continuous/database_build/run.bat, App_Data/jobs/continuous/database_build/settings.job, composer.json, script/hooks/keyboards-build-success.php, tools/db/build/build_cli.php
This uses Kudu continuous webjob to trigger a database build whenever a file .data/MUST_REBUILD is created. This pattern is used from the webhook and also from git deploys (see the PostDeploymentActions for the staging api site).
In the future, we may move to using a triggered webjob, and fire the trigger when needed, but for now this model is simpler.
Fixes #114.
I decided to do this one earlier because of the broken PR https://github.com/keymanapp/keyman.com/pull/194, which was caused by an out-of-date database. Once this merges, I'll re-enable the build configuration step to notify api.keyman-staging.com for the keyboards / models builds and the staging site should then stay in sync with the live site.
=> fix: async database build

web.config
The regexes for version 10-13 for these endpoints was incorrect after tightening the match to only those versions. Note `{R:2}` is likely never needed in any case...
=> fix: update and exception endpoints regexes

_common/KeymanHosts.php, _common/MarkdownHost.php, composer.json, composer.lock
This synchronises the new MarkdownHost class between keymanapp/keyman.com#192 and api.keyman.com.
Note that MarkdownHost is unlikely to be used on api.keyman.com but we need to keep the _common folder in sync anyway.
=> chore: sync common files

.vscode/settings.json, schemas/windows-update/14.0/windows-update.json, script/desktop/10.0/update/index.php, script/windows/14.0/update/WindowsUpdateCheck.php, script/windows/14.0/update/index.php, tests/ReleaseScheduleTest.php, tests/WindowsUpdateCheckTest.php, tools/2020/ReleaseSchedule.php, tools/onlineupdate.php, web.config
Fixes keymanapp/keyman#1635.
This implements the major version upgrade functionality for Keyman on Windows. There are quite a few nuances to take into account:
1. We offer updates for alpha to alpha versions -- they'll never go to beta or stable.
2. Beta versions will be updated to stable, as the beta tier goes stale between major releases.
3. Stable only ever upgrades to stable.
4. We rollout stable major releases gradually to ensure that we don't have hundreds of thousands of users updating at once.
5. Keyman Desktop 10.0 does not currently do major version upgrades, because of a limitation in the installer which means that user keyboards are not migrated (see keymanapp/keyman#3865).
6. This does not support upgrading versions earlier than 10.0 at all.
7. This upgrades Keyman Desktop …
=> feat: major version upgrades (Windows)

schemas/README.md, schemas/developer-update/14.0/developer-update.json, script/developer/14.0/update/DeveloperUpdateCheck.php, script/developer/14.0/update/index.php, tests/DeveloperUpdateCheckTest.php, tests/fixtures/DeveloperUpdateCheck.14.0.json, tests/fixtures/downloads.keyman.com/version/developer/2.0.json, web.config
Relates to keymanapp/keyman#3846.
Adds API endpoint for Keyman Developer 14.0 and later versions which supports tiers and manual updates. Adds basic unit test for same.
See also keymanapp/keyman#3868.
=> feat: Developer major version upgrade support

tools/onlineupdate.php
Adds support for updating Keyman Desktop to latest major stable release, for those versions which support it. This uses the staged rollout pattern from staging PR #122; it is an interim update as the staging branch has a much more complete implementation.
I have tested this locally with versions 11-12 of Keyman Desktop, and version 13 is listed as an update.
=> feat: Windows major upgrade support

tools/onlineupdate.php
onlineupdate.php was return 500 errors on stable site after update as the version of PHP on stable does not support types, unlike the version on staging.
=> fix: php on stable does not support variable types

tools/onlineupdate.php
Setting the release date of 13.0 to 2020-01-01 has the effect of making it available to all users of earlier versions; we haven't had any reported issues with the upgrade so wanting to try and get more users to update.
=> chore: make major upgrade available to all users

App_Data/jobs/continuous/database_build/run.bat
The keyboard build web job needs to ignore the cache in order to always get the latest keyboard and model data.
In theory we could make this signal only for the keyboard and model data and not for the other standards data, but I think that this will be okay anyway, as we don't run more than a handful of builds a day.
=> fix: cached keyboard data not refreshing

tools/db/build/search-prepare-data.sql
The 'deprecated' flag was being ignored when the relationships between keyboards was being built.
See https://github.com/keymanapp/keyman/issues/4207#issuecomment-751243842 for original report
Effective cherry-pick of #138.
=> fix: related keyboards marked as deprecated

_common/KeymanHosts.php, script/search/2.0/search.inc.php, tests/DeveloperUpdateCheckTest.php, tests/Search20Test.php, tools/db/build/sp_keyboard_search.sql, tools/db/build/sp_keyboard_search_alphabetically.sql
Part of keymanapp/keyman.com#206.
* Clamps popularity results to top 100 keyboards
* `p:*` and `p:popularity` (or substring) both work
* Adds alphabetical search
* `p:!` and `p:alphabetically` (or substring) both work
Side fixes:
* Harmonizes KeymanHosts.php with keyman.com
* Removes debug statement from DeveloperUpdateCheckTest.php
=> feat: popularity and alphabetical searches

tools/db/build/common.inc.php
Fixes #143.
If there are additional fields at the end of a row, ignore them. This avoids a problem with a recent iso639-3.tab update as described in #143.
=> fix: Ignore extra fields on tsv import

tools/db/build/sp_keyboard_search.sql
Fixes #147.
The search results for 'german' would return a set of weights for various language codes. 'de' had 5 weights and 'pdt-Latn' had 4, but both had a match on the name 'German' because 'pdt-Latn' has an alternate language name of 'German'. This meant that the actual result returned was indeterminate -- they both had the same weight.
Summing the weights for each language tag match brought 'de' higher in the match results (weight 60 vs 30).
=> fix: improve weight for searches

script/windows/14.0/update/index.php
Relates to keymanapp/keyman#4886.
If a package id has a period or a space (which can happen with legacy packages), then the online update API would not find it, because of a PHP misfeature which transforms these characters in input query parameter names to underscore (really!). This seems like it is potentially impossible to work around for POST requests (`php://input` does not work for `multipart/form-data` duh), so I have added an alternative parameter layout instead. Obviously, this means that Keyman for Windows requires a corresponding update to use the new parameter layout.
=> fix: avoid missing packages with spaces or periods in id

.github/workflows/ci.yml
Fixes #154.
Note that Choco does not currently have support for retries (https://github.com/chocolatey/choco/issues/385).
GitHub Actions have a wrapper for `choco install` called `Choco-Install`, which automatically supports retries. Per comment at https://github.com/actions/virtual-environments/issues/3493#issuecomment-853947713, I am trying this now to see if it does the job for us.
* See actions/virtual-environments#721 for implementation of `Choco-Install`.
=> chore: use Choco-Install script to retry installs

schemas/README.md, schemas/kps/7.0/kps.xsd
Defines a reasonable XML schema for .kps files. This has been [tested](https://github.com/keymanapp/keyboards/pull/1605) against keyboards repository, and it picked up a couple of minor errors within it.
For now, not attempting to build this into Keyman Developer, but will add an xmllint step to keyboards repo soon for .kps files.
Part of keymanapp/keyman#5464.
See the following files for implementations:
* https://github.com/keymanapp/keyman/blob/master/windows/src/global/delphi/general/kpsfile.pas
* https://github.com/keymanapp/keyman/blob/master/windows/src/global/delphi/general/PackageInfo.pas
* https://github.com/keymanapp/keyman/blob/master/developer/js/source/package-compiler/kps-file.ts
* https://github.com/keymanapp/keyman/blob/c8b80ed9866c048e3f2cc943cadb6057a9a62ea5/developer/js …
=> feat: .kps XML Schema

script/desktop/10.0/submitdiag/index.php
Discourse only allows alphanumeric as last char in a username. This makes sure the last char is always alpha by appending 'x'. Rudimentary but should be safe.
=> fix: prevent invalid final char in username

tools/db/build/build_langtags_data_script.inc.php
langtags.json introduced a new metadata tag `_conformance` in release 1.2.2, which was not handled in the database build. The database build now ignores all tags starting with `_`.
=> fix: handle langtags reserved _tags

tools/db/build/datasources.inc.php
I was initialing my local DB via Docker and noticed we're still pulling the raw langtags.json from GitHub.
The WS Tech [langtags API](https://ldml.api.sil.org/langtags.json) is released now (currently v 1.3) so we should be able to use it?
May 🍒 pick to master later.
=> Use langtags API

tools/db/build/sp_keyboard_search.sql
Fixes #197. (I hope!)
When multiple entries in the search sub-result match, the weights will be summed on the assumption that this means the name is more prevalent. For example, German (de) has two entries, whereas German (pdt) has only one.
=> fix: sum search weights when multiple instances of same term

tools/db/build/datasources.inc.php
This updates the links to iso-693-3 with the current link. Also update the URL for LANGTAGS with the released version instead of the staging version.
=> chore: Update URLs

_common/KeymanHosts.php, _common/KeymanSentry.php, build.sh, schemas/model_info.source/1.0.1/model_info.source.json, tests/ModelSearchTest.php, tests/ModelTest.php, tests/manual/validate-kmw-api-transition.php
This updates follows the latest guidance to use .localhost instead of .local on Devs' locally hosted sites
Mirrors keymanapp/help.keyman.com#801
=> chore: Use .localhost instead of .local 🦭

script/desktop/10.0/submitdiag/index.php
Fixes #214.
Discourse API changed at some point so submitting a post would fail with a 422 error due to a change in a field name.
https://meta.discourse.org/t/unable-to-send-a-pm-via-discourseapi-errors-you-must-select-a-valid-user/282943
Ref: https://github.com/discourse/discourse/pull/22561 apparently marked for removal in v2.9.0.
=> fix: error when submitting diagnostic report

mssql.Dockerfile
Recently, my local `./build.sh build` started failing when attempting to install `mssql-server-fts`  due to broken/held package of libldap.
The history on https://hub.docker.com/_/microsoft-mssql-server shows 2022-latest got updated 11/16/2023.
Going to see if pinning the SHA (from the latest GHA) works for me.
-------------
Update:
Pulling a newer sha for 2022-latest and updating the Microsoft packages might be working...
Replacing https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list 
with https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list
=> fix: Pin sha of server:2022-latest 🦭

_control/ready.php
Follows #223 
/_control/ready passes locally on DEVELOPMENT tier, but at the moment, 
https://api.keyman-staging.com/_control/ready
has an error:
> /tools/db/build/cjk/*_import.sql not ready
I think there's some subtle differences between the DEVELOPMENT tier and STAGING tier deployment where the files reside on different containers. (db vs app).
This revises the ready check to use additional db queries to check if it's ready.
I don't know if the check for `tools/db/activeschema.txt` needs to be adjusted too. The info is available on /_control/info.php
and I wonder if this would be adding too much:
`require_once __DIR__ . '/../tools/db/servervars.php';`
=> fix: _control/ready

tools/db/build/search.sql
Fixes #244.
Widens the field to support 3-digit numeric subtags. There may be other metadata we wish to support in the future, but this at least allows the database to build, and searches to return the keyboard in question, verified locally (no tests added at this point).
=> fix: allow numeric region subtags

script/search/2.0/search.inc.php
Moves the filtering earlier in order to get the benefit in the returned object as well as in what we pass to the database.
Fixes: #251
Fixes: API-KEYMAN-COM-1
=> fix: reduce query string length for full text searches

build.sh
Update BOOSTRAP_VERSION to 0.8 to incorporate fix from keymanapp/shared-sites#20
=> chore: Update BOOSTRAP_VERSION to 0.8

script/desktop/10.0/submitdiag/index.php
Discourse API changed with a recent update to community.software.sil.org.
Fixes: keymanapp/keyman#12678
=> fix(windows): track discourse field name change for upload.json

build.sh, tools/2020/DownloadsApi.php, tools/2020/SKeymanComApi.php, tools/onlineupdate.php
* Splits the server-side and client-side references to keyman sites so that docker-based PHP can reference host.docker.internal on development machines for cross-references.
* Removes some links to legacy sites such as sentry.keyman.com.
Relates-to: keymanapp/shared-sites#53
Relates-to: keymanapp/keyman.com#545
=> refactor: clean up KeymanHosts usage and make consistent

script/search/1.0/search.php, script/search/2.0/search.php
An empty search query is expensive and should not be permitted, as it returns every record in the keyboard table, rather than a subset.
Note: this is a mitigation, as no rate limiting is supported. v2.0 search supports paging, so perhaps we should consider retiring v1.0 search altogether.
=> chore: restrict empty search query

build.sh
Make `build.sh start` idempotent, so (a) build action does not need to be run separately, and (b) it won't fail if the site/database containers are already running.
Relates-to: keymanapp/shared-sites#79
Test-bot: skip
=> feat: idempotent start action
