keymanapp/api.keyman.com

- tools/onlineupdate.php
This is so that stable versions in the same major release are offered once they become available.
Later, we need to complete the work referred to:
// TODO: Offer upgrades for MAJOR.x.x.x versions.
// We still don't support staying on alpha or beta tier once a version
// hits stable. We need to review the upgrade strategies for these.
// Once a version is older than latest stable, we also don't offer updates for it; 
// this is probably also wrong.
Also, see https://github.com/keymanapp/keyman/issues/1635
Raised at https://community.software.sil.org/t/bug-in-keyman-developer-11/2047/8
> Check updates with defined tier order stable,beta,alpha.

- tools/db/build/build_keyboards_script.php
- tools/db/build/build_models_script.php
- tools/db/build/common.php
> [api.keyman.com] Purge destination folders before unzipping model_info.zip and keyboard_info.zip during database build

- web.config
> Add endpoints for Keyman Desktop/Developer 12.0

- schemas/readme.MD
- schemas/visualkeyboard/visualkeyboard.dtd
There will be a corresponding PR from tavultesoft.com shortly.
> Move DTD from tavultesoft.com to api.keyman.com

- schemas/readme.MD
- schemas/version/2.0/version.json
- script/version/version.php
- tools/keymanversion.php
> Add linux as platform for version query

- tools/db/build/build_keyboards_script.php
- tools/db/build/build_models_script.php
> fix: two more lower case locations for bcp 47

- script/legacy/legacy30.php
- script/legacy/legacy40.php
Fixes #35.
See for example: https://api.keyman.com/cloud/4.0/keyboards/uzbek; if you run on a local instance then you'll get notices and warnings per #35; this fixes those notices and warnings.
> fix: legacy api giving log errors.

- schemas/package-version/1.0/package-version.json
- schemas/readme.MD
- schemas/web.config
- script/package-version/package-version.php
- web.config
> feat: add package-version api

- script/search/2.0/search.inc.php
- tests/Search20Test.php
- tests/fixtures/Search.2.0.khmer.json
- tools/db/build/sp_keyboard_search.sql
language id searching will come later as an alternate context. Also adds an extra Unicode search test
> fix: keyboard id search

- script/search/2.0/search.inc.php
- tests/Search20Test.php
- tools/db/build/sp_keyboard_search.sql
- tools/db/build/sp_keyboard_search_by_popularity.sql
It was cleaning too many classes of Unicode characters before search.
> fix: clean string was too aggressive

- composer.json
- script/keyboard/keyboard.php
- script/legacy/legacy10.php
- script/legacy/legacy20.php
- script/legacy/legacy30.php
- script/legacy/legacy40.php
- script/model-search/model-search.php
- script/model/model.php
- script/package-version/package-version.inc.php
- script/package-version/package-version.php
- script/search/1.0/search.php
- script/search/2.0/search.php
- script/version/version.php
- tests/fixtures/WindowsUpdateCheck.14.0.json
- tests/rest/RestCloudTest.php
- tests/rest/RestTestCase.php
- tools/2020/KeymanHosts.php
- web.config
Remove hard-coded references to any *.keyman.com domains and replace with KeymanHosts. Update KeymanHosts to use keyman-staging.com.
> chore: update host names

- script/search/2.0/search.inc.php
Relates to #87.
Challenger for smallest PR on the Keyman project so far.
> fix: n'ko not found

- tools/db/build/search.sql
This avoids issues deleting tables due to FK constraints.
> fix: change table deletion order

- script/package-version/package-version.inc.php
> feat: use go/package for model package-version api

- tools/db/build/indexes.sql
Part of #107.
This improves the indexes for short searches.
> chore: improve indexes

- script/desktop/10.0/submitdiag/index.php
Fixes keymanapp/keyman#3673.
Discourse's API authentication has changed, so we needed to rework to remove old ways of doing things. Also tweaked some of the error handling to make it slightly easier to track in the future.
> fix: diagnostic endpoint discourse update

- README.md
- tools/db/servervars.php
Add production_k0 and production_k1 users to the Azure database for the production site.
> chore: production site

- index.php
- tools/db/build/build_cli.php
Fixes #130.
Didn't turn this into an API as we only need this information for
diagnostic purposes. Makes life simpler when trying to figure out what
is going on with keyboard deployment, etc.
> chore: simple api state

- schemas/regtest/README.md
- schemas/regtest/regtest.dtd
> fix: add regtest.dtd schema

- script/desktop/10.0/submitdiag/index.php
> chore: Merge master from Sprint a17s2 to staging

- composer.json
- composer.lock
> chore: Merge master branch from Sprint A17S7

- build.sh
- resources/builder.inc.sh
- tools/db/build/build.inc.php
Follow-on to #180 and part of keymanapp/keyman.com#337
This updates `sleep` before attempting to connect to the db for initialization. Timing will depend on particular machine:
* `build.sh start` - Change from 5s to 15s sleep before attemtping to initialize db
* build.inc.php - Add sleep(10) to the tries loop.
Additional changes
* Update builder.inc.sh and builder-isms
* Cleanup undefined variable in _stop_docker_container
> fix: Timing to ensure db ready to connect 🦭

- composer.lock
> Merge Master from Sprint A17S12 to staging

- .htaccess
- Dockerfile
- build.sh
- resources/builder.inc.sh
- tools/db/servervars.php
also removes unused S_KEYMAN_COM variable
TODO: update ci.yml
> fix: staging tests, memory alloc, and env vars

- .github/workflows/cleanup.yml
- .github/workflows/docker.yml
Auto build Docker images for staging and master braches, and push.  Doesn't push for pull requests, but still builds.
> Add GHA workflows to build and manage docker images

- tools/db/build/sp_keyboard_search.sql
Fixes #197 in same was as #148. See #201 for discussion.
Note, once this is approved and merged, will update #200 with this and that will replace #201.
> fix: use alternate select to improve search weights

- .gitattributes
- Dockerfile
- build.sh
- resources/init-container.sh
Continuing keymanapp/keyman.com#337
* Update usage of shared-sites bootstrapper. Still needed custom steps for:
* build:db
* start:db
* start:app
* Split DB creation to init-container.sh
* Update test action
> chore: Add init-container.sh 🦭

- build.sh
Follows the pattern from keymanapp/shared-site#8
> fix: Use --add-host parameter on Linux host

- .htaccess
> chore: pass webhook token in .htaccess rewrite

- README.md
Trivial change to README to trigger webhook
> chore: Update readme to trigger webhook

- .htaccess
- _control/ready.php
Addresses the point for https://github.com/keymanapp/keyman.com/issues/403
> api.keyman.com
>
> *test db connection, build status, as well as web server ready, and _common files, vendor files ready
> .htaccess rewrite from /_control/ready to /_control/ready.php
> chore: Add /_control/ready

- build.sh
:cherries: pick of #225 to production
> Update production to use shared-sites v0.4 :cherries: 

- Dockerfile
- composer.json
- resources/init-container.sh
- tests/data/README.md
> fix: force re-download of data when building database

- script/legacy/legacy40.php
Fixes: #247
Fixes: API-KEYMAN-COM-2K
> fix: handle missing properties in language examples

- .gitignore
- .htaccess
- .user.ini
- build.sh
Relates-to: keymanapp/keyman.com#494
Depends-on: keymanapp/shared-sites#38
> chore: support debug mode

- schemas/kps/18.0/kps.xsd
- schemas/kps/README.md
From keymanapp/keyman#13600, keymanapp/keyman#13640.
> chore: add v18.0 kps schema

- tools/db/build/build.inc.php
We started to see situations where status checks for new PRs would fail, for example see #290, with hard to parse errors about actual search results mismatching expected results. After digging in, with a lot of logging and debugging, I found that the issue was a race where the test would run before full text indexing had completed. This change delays the completion of the database build until the full text indexing has finished.
The full description of my investigation is recorded in #290 for future reference.
Test-bot: skip
> fix: wait for full text indexing to complete when building database

- build.sh
> auto: A19S12 merge master into staging
